# Allows onlishop to push to administration, core, elasticsearch & storefront

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:onlishop/onlishop:environment:manyrepos.*
claim_pattern:
  workflow_ref: onlishop/onlishop/.github/workflows/(05-prepare-release|nightly).yml@.*

permissions:
  contents: write

repositories:
  - administration
  - core
  - elasticsearch
  - storefront